Repository TempleEight/spec-golang, pull requests merged in 2020-04, with the labels that each got.

#102 [user] Add read picture endpoint
  user/dao/dao.go
  user/dao/errors.go
  user/hook.go
  user/metric/metric.go
  user/user.go
  user/user_test.go
  user/util/util.go
Labels: size/L

#103 [kube-metrics] Add metrics to kube
  deploy.sh
  kube/auth/auth-service.yaml
  kube/grafana/grafana-deployment.yaml
  kube/grafana/grafana-service.yaml
  kube/match/match-service.yaml
  kube/prom/prometheus-deployment.yaml
  kube/prom/prometheus-service.yaml
  kube/user/user-service.yaml
Labels: size/L

#105 [auth] Rename hooks to register and login
  auth/auth.go
  auth/auth_test.go
  auth/hook.go
Labels: size/M

#104 [user] Add update picture endpoint
  user/dao/dao.go
  user/hook.go
  user/metric/metric.go
  user/user.go
  user/user_test.go
Labels: size/L

#106 [user] Add delete picture endpoint
  user/dao/dao.go
  user/hook.go
  user/metric/metric.go
  user/user.go
  user/user_test.go
Labels: size/L

#107 [open-api] Update schema with picture endpoints
  api/spec-golang.openapi.yaml
Labels: size/L

#108 [match] Remove server set values from SQL query and use hooks instead
  match/dao/dao.go
  match/dao/errors.go
  match/setup.go
Labels: size/M

#109 Release/0.3.0
  .travis.yml
  api/spec-golang.openapi.yaml
  auth/auth.go
  auth/auth_it_test.go
  auth/auth_test.go
  auth/config.json
  auth/dao/dao.go
  auth/dao/datastore.go
  auth/go.mod
  auth/go.sum
  auth/hook.go
  auth/metric/metric.go
  auth/setup.go
  auth/util/config.go
  deploy.sh
  docker-compose.yml
  grafana/provisioning/dashboards/auth.json
  grafana/provisioning/dashboards/dashboards.yml
  grafana/provisioning/dashboards/match.json
  grafana/provisioning/dashboards/user.json
  grafana/provisioning/datasources/datasource.yml
  kong/configure-kong-k8s.sh
  kube/auth/auth-service.yaml
  kube/grafana/grafana-deployment.yaml
  kube/grafana/grafana-service.yaml
  kube/match/match-service.yaml
  kube/prom/prometheus-deployment.yaml
  kube/prom/prometheus-service.yaml
  kube/user/user-service.yaml
  match/config.json
  match/dao/dao.go
  match/dao/datastore.go
  match/dao/errors.go
  match/go.mod
  match/go.sum
  match/hook.go
  match/match.go
  match/match_it_test.go
  match/match_test.go
  match/metric/metric.go
  match/setup.go
  match/util/config.go
  prometheus/prometheus.yml
  push-image.sh
  user-db/init.sql
  user/config.json
  user/dao/dao.go
  user/dao/datastore.go
  user/dao/errors.go
  user/go.mod
  user/go.sum
  user/hook.go
  user/metric/metric.go
  user/setup.go
  user/user.go
  user/user_it_test.go
  user/user_test.go
  user/util/config.go
  user/util/util.go
Labels: size/XXL

#110 Update develop
  push-image.sh
Labels: size/XS

#111 [grafana] Update grafana to show picture metrics
  grafana/provisioning/dashboards/user.json
Labels: size/XL

#112 [readme] Add README
  README.md
Labels: size/S
