Repository TempleEight/spec-golang, pull requests merged in 2020-02, with the labels that each got.

#9 [tidy] Optimise DAO and add configuration file handling for User service
  build.sh
  user-db/init.sql
  user/Dockerfile
  user/config.json
  user/dao/user-dao.go
  user/user.go
  user/utils/config.go
  user/utils/utils.go
Labels: size/L

#11 [tidy] Misc fixes to User and Match services
  docker-compose.yml
  match/dao/match-dao.go
  match/match.go
  user-db/init.sql
  user/dao/user-dao.go
  user/user.go
  user/utils/utils.go
Labels: size/L

#12 [tidy] Fix all matches endpoint
  kong/configure-kong.sh
  match/dao/match-dao.go
  match/match.go
Labels: size/M

#14 [infra] Use go modules
  match/Dockerfile
  match/go.mod
  match/go.sum
  user/Dockerfile
  user/go.mod
  user/go.sum
Labels: size/S

#13 [Go-Gen] Implement Cross-Service Communication
  match/comm/handler.go
  match/config.json
  match/dao/match-dao.go
  match/match.go
  match/utils/config.go
  user/dao/user-dao.go
  user/user.go
Labels: size/M

#15 Release v0.1.0
  .gitignore
  build.sh
  docker-compose.yml
  kong/configure-kong.sh
  match-db/init.sql
  match/Dockerfile
  match/comm/handler.go
  match/config.json
  match/dao/errors.go
  match/dao/match-dao.go
  match/go.mod
  match/go.sum
  match/match.go
  match/utils/config.go
  match/utils/utils.go
  user-db/init.sql
  user/Dockerfile
  user/config.json
  user/dao/errors.go
  user/dao/user-dao.go
  user/go.mod
  user/go.sum
  user/user.go
  user/utils/config.go
  user/utils/utils.go
Labels: size/XL

#17 [auth] Add a basic auth service
  auth-db/init.sql
  auth/Dockerfile
  auth/auth.go
  auth/config.json
  auth/dao/auth-dao.go
  auth/go.mod
  auth/go.sum
  auth/utils/config.go
  auth/utils/utils.go
  docker-compose.yml
  kong/configure-kong.sh
Labels: size/L

#19 [match] Move error check prior to comms init
  match/match.go
Labels: size/XS

#18 [auth] Register a new email/password combination and return a JWT
  .gitignore
  auth/auth.go
  auth/dao/auth-dao.go
  auth/go.mod
  auth/go.sum
  auth/utils/utils.go
Labels: size/M

#20 [auth] Request JWT secret from Kong
  auth/Dockerfile
  auth/auth.go
  auth/comm/handler.go
  auth/config.json
  auth/wait-for-kong.sh
  docker-compose.yml
  kong/configure-kong.sh
Labels: size/L

#21 [auth] Allow existing users to login and receive a *fresh* auth token
  auth/auth.go
  auth/dao/auth-dao.go
  auth/dao/errors.go
Labels: size/L
