Repository TempleEight/spec-golang, pull requests merged in 2020-03, with the labels that each got.

#23 [go-gen] Update to match generated files
  match/comm/handler.go
  match/dao/dao.go
  match/dao/errors.go
  match/go.sum
  match/match.go
  match/util/config.go
  match/util/util.go
  match/utils/config.go
  user/dao/dao.go
  user/user.go
  user/util/config.go
  user/util/util.go
  user/utils/config.go
Labels: size/L

#24 [go-gen] Add checkUser call to update match
  match/match.go
Labels: size/M

#22 [k8s] Kong Kubernetes Infrastructure
  K8s-DEPLOYMENT.md
  kube/kong/kong-db-deployment.yaml
  kube/kong/kong-db-service.yaml
  kube/kong/kong-deployment.yaml
  kube/kong/kong-migration-job.yaml
  kube/kong/kong-service.yaml
Labels: size/L

#25 [auth] validate exp claim via Kong
  kong/configure-kong.sh
Labels: size/XS

#29 [go-gen] Add returning responses to CREATE and UPDATE endpoints
  auth/dao/dao.go
  match/dao/dao.go
  match/match.go
  user/dao/dao.go
  user/user.go
Labels: size/L

#27 [k8s] Implement Service-Level K8s Config
  kube/deploy.sh
  kube/match/match-db-deployment.yaml
  kube/match/match-db-service.yaml
  kube/match/match-db-storage.yaml
  kube/match/match-deployment.yaml
  kube/match/match-service.yaml
  kube/user/user-db-deployment.yaml
  kube/user/user-db-service.yaml
  kube/user/user-db-storage.yaml
  kube/user/user-deployment.yaml
  kube/user/user-service.yaml
Labels: size/L

#30 [auth] replaces email address in JWT with unique ID
  auth/auth.go
  auth/dao/dao.go
Labels: size/M

#31 [user] Generalise database types to allow for dependency injection
  user/dao/dao.go
  user/user.go
Labels: size/M

#35 [API] Start the OpenAPI file
  api/spec-golang.openapi.yaml
Labels: size/M

#33 [match] Generalise match datastore using interface
  match/comm/handler.go
  match/dao/dao.go
  match/match.go
Labels: size/M

#34 [auth] Generalise auth datastore using interface
  auth/auth.go
  auth/comm/handler.go
  auth/dao/dao.go
Labels: size/M

#37 [API] Add index.html for browser-based docs
  index.html
Labels: size/S

#36 [k8s] Integrate Kong and Services for end to end K8s config
  K8s-DEPLOYMENT.md
  deploy.sh
  kong/configure-kong-k8s.sh
  kube/auth/auth-db-deployment.yaml
  kube/auth/auth-db-service.yaml
  kube/auth/auth-db-storage.yaml
  kube/auth/auth-deployment.yaml
  kube/auth/auth-service.yaml
  kube/deploy.sh
Labels: size/L

#39 [API] Add the entire match service to OpenAPI
  api/spec-golang.openapi.yaml
  index.html
Labels: size/L

#41 [API] Add the user service to the OpenAPI spec
  api/spec-golang.openapi.yaml
Labels: size/L

#38 Initial testing infra
  .travis.yml
  user/user_test.go
Labels: size/L

#42 [user][test] Add additional unit tests for the user service
  user/user.go
  user/user_test.go
Labels: size/L

#43 [match][test] Add unit test basis for match service
  match/go.sum
  match/match.go
  match/match_test.go
Labels: size/L

#44 [auth][test] Add unit test basis for auth service
  auth/auth.go
  auth/auth_test.go
  auth/go.mod
Labels: size/L

#45 [auth][test] Add additional tests for auth
  auth/auth.go
  auth/auth_test.go
Labels: size/L

#46 [auth] Make email unique on auth service
  auth-db/init.sql
  auth/auth.go
  auth/auth_test.go
  auth/dao/dao.go
  auth/dao/errors.go
Labels: size/M

#47 [user][dao] Move request response types from DAO
  user/dao/dao.go
  user/user.go
  user/user_test.go
Labels: size/L

#48 [user][test] Make tests consistent between endpoints
  user/user_test.go
Labels: size/L

#49 [auth][test] Move request / response types and make tests consistent
  auth/auth.go
  auth/auth_test.go
  auth/dao/dao.go
Labels: size/L

#51 [go-gen] Move request/response types from DAO in Match service, and increase consistency
  auth/auth.go
  auth/dao/dao.go
  match-db/init.sql
  match/comm/handler.go
  match/dao/dao.go
  match/match.go
  match/match_test.go
  user-db/init.sql
  user/dao/dao.go
  user/user.go
Labels: size/L

#53 [auth] Add JSON content type header to each response
  auth/auth.go
Labels: size/XS

#50 [user][auth] Store AuthID alongside user and validate in requests
  user-db/init.sql
  user/dao/dao.go
  user/go.mod
  user/go.sum
  user/user.go
  user/user_test.go
  user/util/util.go
Labels: size/L

#54 [go-gen] Make test structs and globals private
  auth/auth_test.go
  match/match_test.go
  user/user_test.go
Labels: size/L

#55 [auth][user] Add additional handler for user auth
  user/dao/dao.go
  user/user.go
  user/user_test.go
Labels: size/L

#56 [go-gen] Add unit tests to Match service
  match/match_test.go
  user/user_test.go
Labels: size/L

#57 [test] Integration tests
  .travis.yml
  user/docker-compose.yml
  user/test.Dockerfile
  user/user_it_test.go
Labels: size/L

#59 [auth][user] Remove auth ID
  user-db/init.sql
  user/dao/dao.go
  user/user.go
  user/user_it_test.go
  user/user_test.go
Labels: size/L

#61 [api] Add URL parameter comments to the OpenAPI spec
  api/spec-golang.openapi.yaml
Labels: size/S

#62 [user][auth] Use ID from JWT when storing user
  api/spec-golang.openapi.yaml
  auth/auth.go
  auth/auth_test.go
  user-db/init.sql
  user/dao/dao.go
  user/dao/errors.go
  user/go.mod
  user/go.sum
  user/user.go
  user/user_it_test.go
  user/user_test.go
  user/util/util.go
Labels: size/L

#65 [user][auth] Use google UUID package
  user/dao/dao.go
  user/go.mod
  user/go.sum
  user/user.go
  user/util/util.go
Labels: size/S

#66 [auth] Use UUID for auth service
  auth-db/init.sql
  auth/auth.go
  auth/auth_test.go
  auth/dao/dao.go
  auth/go.mod
  auth/go.sum
Labels: size/M

#67 [auth] Add integration tests for auth
  .travis.yml
  auth/auth.go
  auth/auth_it_test.go
  auth/comm/handler.go
  auth/dao/dao.go
  auth/docker-compose.yml
  auth/test.Dockerfile
  auth/util/config.go
  auth/util/util.go
  auth/utils/config.go
  user/docker-compose.yml
Labels: size/L

#69 [user] One-line mock env
  user/user_test.go
Labels: size/M

#68 [auth] One-line mock env
  auth/auth_test.go
Labels: size/M

#63 [go-gen] Add auth to the Match service
  auth-db/init.sql
  match-db/init.sql
  match/dao/dao.go
  match/go.mod
  match/go.sum
  match/match.go
  match/match_test.go
  match/util/util.go
  user-db/init.sql
  user/user_test.go
Labels: size/L

#72 [go-gen] Change IDs to UUIDs and update tests in Match service
  match-db/init.sql
  match/comm/handler.go
  match/dao/dao.go
  match/dao/errors.go
  match/go.mod
  match/go.sum
  match/match.go
  match/match_test.go
  match/util/util.go
Labels: size/L

#71 [user] Extract UUID to constant and rename JWTs
  user/user_it_test.go
  user/user_test.go
Labels: size/M

#74 [match] Use RFC3339/ISO8601 for time formatting throughout
  match-db/init.sql
  match/comm/handler.go
  match/dao/dao.go
  match/match.go
  match/match_test.go
Labels: size/L

#73 [match] Add integration tests for match service
  .travis.yml
  match/docker-compose.yml
  match/match.go
  match/match_it_test.go
  match/test.Dockerfile
Labels: size/L

#76 [auth] Make register and login endpoints POST
  auth/auth.go
  auth/auth_it_test.go
  auth/auth_test.go
Labels: size/M

#78 [go-gen] Rename auth_id to created_by in datastore
  match-db/init.sql
  match/dao/dao.go
  match/match.go
  match/match_it_test.go
  match/match_test.go
Labels: size/M

#77 [openapi-gen] Update openapi spec
  api/spec-golang.openapi.yaml
Labels: size/XL

#80 [user][hook] Add hook for create endpoint
  user/hook.go
  user/setup.go
  user/user.go
  user/user_it_test.go
  user/user_test.go
Labels: size/M

#81 [user][hook] Add read, update & delete hooks
  user/hook.go
  user/user.go
Labels: size/L

#82 [user][hooks] Allow router configuration
  user/setup.go
  user/user.go
Labels: size/S

#83 [hooks] Extend datastore type
  .travis.yml
  auth/dao/dao.go
  auth/dao/datastore.go
  match/dao/dao.go
  match/dao/datastore.go
  user/dao/dao.go
  user/dao/datastore.go
  user/user_test.go
Labels: size/M

#84 [match][hooks] Add hook types
  match/hook.go
  match/match.go
  match/match_it_test.go
  match/match_test.go
  match/setup.go
Labels: size/L

#85 [user] Add unit tests for hooks
  user/user_test.go
Labels: size/L

#86 [match][hooks] Add hook logic and test for create and read
  match/match.go
  match/match_test.go
Labels: size/L

#87 [match][hooks] Add hook logic and tests for update, delete and list endpoints
  match/hook.go
  match/match.go
  match/match_test.go
Labels: size/XL

#88 [auth][hooks] Add hooks to auth service
  auth/auth.go
  auth/auth_test.go
  auth/hook.go
  auth/setup.go
Labels: size/L

#89 [metrics] Add bare bones metrics config, with grafana and prometheus
  docker-compose.yml
  grafana/provisioning/dashboards/dashboards.yml
  grafana/provisioning/dashboards/user.json
  grafana/provisioning/datasources/datasource.yml
  prometheus/prometheus.yml
  user/go.mod
  user/go.sum
  user/user.go
Labels: size/L

#90 [metrics][user] Add custom metrics to the user service
  grafana/provisioning/dashboards/user.json
  user/metric/metric.go
  user/user.go
Labels: size/L

#91 [user] Replace error responses with util function
  user/user.go
Labels: size/M

#92 [metrics][user] Add database query time metric
  grafana/provisioning/dashboards/user.json
  user/metric/metric.go
  user/user.go
Labels: size/L

#93 [match] Add error util function
  match/match.go
  match/metric/metric.go
Labels: size/L

#95 [metrics][match] Add metrics to match service
  docker-compose.yml
  grafana/provisioning/dashboards/match.json
  match/go.mod
  match/go.sum
  match/match.go
  match/metric/metric.go
  prometheus/prometheus.yml
Labels: size/XL

#94 [auth][hooks] Call setup method from main
  auth/auth.go
  auth/auth_it_test.go
  auth/auth_test.go
Labels: size/S

#96 [auth] Auth error util
  auth/auth.go
  auth/metric/metric.go
Labels: size/M

#98 [metrics][auth] Add metrics for auth service
  auth/auth.go
  auth/go.mod
  auth/go.sum
  auth/metric/metric.go
  docker-compose.yml
  grafana/provisioning/dashboards/auth.json
  grafana/provisioning/dashboards/user.json
  prometheus/prometheus.yml
Labels: size/L

#97 [Infra] Add travis stage to build and push images
  .travis.yml
  push-image.sh
Labels: size/S

#99 [config] Move ports to config file
  auth/auth.go
  auth/config.json
  auth/util/config.go
  match/config.json
  match/match.go
  match/util/config.go
  user/config.json
  user/user.go
  user/util/config.go
Labels: size/M

#100 [deploy] Add basedir to files
  deploy.sh
  kong/configure-kong-k8s.sh
Labels: size/S

#101 [user] Add picture struct create endpoint
  user-db/init.sql
  user/dao/dao.go
  user/hook.go
  user/metric/metric.go
  user/user.go
  user/user_test.go
Labels: size/L
